[INFO     2012-03-09 15:09:01,814 bulkloader.py] Logging to bulkloader-log-20120309.150901
[INFO     2012-03-09 15:09:01,815 bulkloader.py] Throttling transfers:
[INFO     2012-03-09 15:09:01,816 bulkloader.py] Bandwidth: 250000 bytes/second
[INFO     2012-03-09 15:09:01,816 bulkloader.py] HTTP connections: 8/second
[INFO     2012-03-09 15:09:01,816 bulkloader.py] Entities inserted/fetched/modified: 20/second
[INFO     2012-03-09 15:09:01,816 bulkloader.py] Batch Size: 10
[INFO     2012-03-09 15:09:01,905 bulkloader.py] Opening database: bulkloader-progress-20120309.150901.sql3
[DEBUG    2012-03-09 15:09:01,937 adaptive_thread_pool.py] [Thread-1] WorkerThread: started
[DEBUG    2012-03-09 15:09:01,937 adaptive_thread_pool.py] [Thread-2] WorkerThread: started
[DEBUG    2012-03-09 15:09:01,938 adaptive_thread_pool.py] [Thread-3] WorkerThread: started
[DEBUG    2012-03-09 15:09:01,938 adaptive_thread_pool.py] [Thread-4] WorkerThread: started
[DEBUG    2012-03-09 15:09:01,938 adaptive_thread_pool.py] [Thread-5] WorkerThread: started
[DEBUG    2012-03-09 15:09:01,939 adaptive_thread_pool.py] [Thread-6] WorkerThread: started
[DEBUG    2012-03-09 15:09:01,957 adaptive_thread_pool.py] [Thread-7] WorkerThread: started
[DEBUG    2012-03-09 15:09:01,958 adaptive_thread_pool.py] [Thread-8] WorkerThread: started
[DEBUG    2012-03-09 15:09:01,958 adaptive_thread_pool.py] [Thread-9] WorkerThread: started
[DEBUG    2012-03-09 15:09:01,962 adaptive_thread_pool.py] [Thread-10] WorkerThread: started
[DEBUG    2012-03-09 15:09:01,962 bulkloader.py] Configuring remote_api. url_path = /remote_api, servername = localhost:8080
[DEBUG    2012-03-09 15:09:11,035 bulkloader.py] Bulkloader using app_id: ericvv125fw
[INFO     2012-03-09 15:09:11,036 bulkloader.py] Connecting to localhost:8080/remote_api
[DEBUG    2012-03-09 15:09:11,465 bulkloader.py] [Thread-11] ProgressTrackerThread: started
[DEBUG    2012-03-09 15:09:11,466 bulkloader.py] [Thread-12] DataSourceThread: started
[INFO     2012-03-09 15:09:11,466 bulkloader.py] Starting import; maximum 10 entities per post
[DEBUG    2012-03-09 15:09:11,526 adaptive_thread_pool.py] [Thread-1] Got work item [1-10]
[ERROR    2012-03-09 15:09:11,590 adaptive_thread_pool.py] [Thread-1] WorkerThread:
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/adaptive_thread_pool.py", line 176, in WorkOnItems
    status, instruction = item.PerformWork(self.__thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 764, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 935, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 1420, in PostEntities
    datastore.Put(entities)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/datastore.py", line 575, in Put
    return PutAsync(entities, **kwargs).get_result()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/datastore/datastore_rpc.py", line 777, in get_result
    results = self.__rpcs[0].get_result()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 592, in get_result
    return self.__get_result_hook(self)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/datastore/datastore_rpc.py", line 1547, in __put_hook
    self.check_rpc_success(rpc)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/datastore/datastore_rpc.py", line 1184, in check_rpc_success
    raise _ToDatastoreError(err)
BadRequestError: app "dev~ericvv125fw" cannot access app "ericvv125fw"'s data
[DEBUG    2012-03-09 15:09:11,596 adaptive_thread_pool.py] [Thread-1] WorkerThread: exiting
[INFO     2012-03-09 15:09:11,597 adaptive_thread_pool.py] [Thread-2] Backing off due to errors: 1.0 seconds
[INFO     2012-03-09 15:09:11,717 bulkloader.py] Unexpected thread death: Thread-1
[INFO     2012-03-09 15:09:11,717 bulkloader.py] An error occurred. Shutting down...
[DEBUG    2012-03-09 15:09:11,722 adaptive_thread_pool.py] [Thread-4] WorkerThread: exiting
[DEBUG    2012-03-09 15:09:11,722 adaptive_thread_pool.py] [Thread-5] WorkerThread: exiting
[DEBUG    2012-03-09 15:09:11,722 adaptive_thread_pool.py] [Thread-8] WorkerThread: exiting
[DEBUG    2012-03-09 15:09:11,723 adaptive_thread_pool.py] [Thread-9] WorkerThread: exiting
[DEBUG    2012-03-09 15:09:11,723 adaptive_thread_pool.py] [Thread-3] WorkerThread: exiting
[DEBUG    2012-03-09 15:09:11,723 adaptive_thread_pool.py] [Thread-7] WorkerThread: exiting
[DEBUG    2012-03-09 15:09:11,723 adaptive_thread_pool.py] [Thread-10] WorkerThread: exiting
[DEBUG    2012-03-09 15:09:11,723 adaptive_thread_pool.py] [Thread-6] WorkerThread: exiting
[DEBUG    2012-03-09 15:09:11,724 bulkloader.py] [Thread-12] DataSourceThread: exiting
[DEBUG    2012-03-09 15:09:11,726 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-03-09 15:09:11,726 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-03-09 15:09:11,847 adaptive_thread_pool.py] [Thread-2] WorkerThread: exiting
[DEBUG    2012-03-09 15:09:11,847 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-03-09 15:09:11,847 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-03-09 15:09:11,848 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-03-09 15:09:11,848 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-03-09 15:09:11,848 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-03-09 15:09:11,848 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-03-09 15:09:11,848 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-03-09 15:09:11,848 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[ERROR    2012-03-09 15:09:11,848 adaptive_thread_pool.py] Error in Thread-1: app "dev~ericvv125fw" cannot access app "ericvv125fw"'s data
[DEBUG    2012-03-09 15:09:11,848 adaptive_thread_pool.py] Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/adaptive_thread_pool.py", line 176, in WorkOnItems
    status, instruction = item.PerformWork(self.__thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 764, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 935, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 1420, in PostEntities
    datastore.Put(entities)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/datastore.py", line 575, in Put
    return PutAsync(entities, **kwargs).get_result()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/datastore/datastore_rpc.py", line 777, in get_result
    results = self.__rpcs[0].get_result()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 592, in get_result
    return self.__get_result_hook(self)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/datastore/datastore_rpc.py", line 1547, in __put_hook
    self.check_rpc_success(rpc)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/datastore/datastore_rpc.py", line 1184, in check_rpc_success
    raise _ToDatastoreError(err)
BadRequestError: app "dev~ericvv125fw" cannot access app "ericvv125fw"'s data

[DEBUG    2012-03-09 15:09:11,849 bulkloader.py] Waiting for progress_thread to terminate...
[DEBUG    2012-03-09 15:09:11,875 bulkloader.py] [Thread-11] ProgressTrackerThread: exiting
[DEBUG    2012-03-09 15:09:11,881 bulkloader.py] ... done.
[INFO     2012-03-09 15:09:11,881 bulkloader.py] 1020 entities total, 0 previously transferred
[INFO     2012-03-09 15:09:11,881 bulkloader.py] 0 entities (1482 bytes) transferred in 10.1 seconds
[INFO     2012-03-09 15:09:11,881 bulkloader.py] Some entities not successfully transferred
